INSERT INTO timezones (name, utc_offset) VALUES ('Линия перемены дат', '-12');
INSERT INTO timezones (name, utc_offset) VALUES ('Гавайи', '-10');
INSERT INTO timezones (name, utc_offset) VALUES ('Аляска', '-9');
INSERT INTO timezones (name, utc_offset) VALUES ('Тихоокеанское время (США и Канада)', '-8');
INSERT INTO timezones (name, utc_offset) VALUES ('Аризона', '-7');
INSERT INTO timezones (name, utc_offset) VALUES ('Центральная Америка', '-6');
INSERT INTO timezones (name, utc_offset) VALUES ('Восточное время (США и Канада)', '-5');
INSERT INTO timezones (name, utc_offset) VALUES ('Атлантическое время (Канада)', '-4');
INSERT INTO timezones (name, utc_offset) VALUES ('Бразилия', '-3');
INSERT INTO timezones (name, utc_offset) VALUES ('Азорские острова', '-1');
INSERT INTO timezones (name, utc_offset) VALUES ('Лондон', '');
INSERT INTO timezones (name, utc_offset) VALUES ('Берлин', '+1');
INSERT INTO timezones (name, utc_offset) VALUES ('Калиниград', '+2');
INSERT INTO timezones (name, utc_offset) VALUES ('Москва', '+3');
INSERT INTO timezones (name, utc_offset) VALUES ('Самара', '+4');
INSERT INTO timezones (name, utc_offset) VALUES ('Екатеринбург', '+5');
INSERT INTO timezones (name, utc_offset) VALUES ('Омск', '+6');
INSERT INTO timezones (name, utc_offset) VALUES ('Новосибирск', '+7');
INSERT INTO timezones (name, utc_offset) VALUES ('Иркутск', '+8');
INSERT INTO timezones (name, utc_offset) VALUES ('Чита', '+9');
INSERT INTO timezones (name, utc_offset) VALUES ('Владивосток', '+10');
INSERT INTO timezones (name, utc_offset) VALUES ('Сахалин', '+11');
INSERT INTO timezones (name, utc_offset) VALUES ('Камчатка', '+12');
INSERT INTO timezones (name, utc_offset) VALUES ('Самоа', '+13');